"""PDF generation for complaint letters and analysis reports.

Uses fpdf2 — lightweight, no heavy dependencies.
"""

from __future__ import annotations

import os
import tempfile
from datetime import datetime
from io import BytesIO
from pathlib import Path
from typing import Optional

from fpdf import FPDF


class ComplaintPDF(FPDF):
    """Formal Nepali legal complaint letter PDF."""

    def header(self):
        self.set_font("Helvetica", "B", 10)
        self.set_text_color(180, 150, 80)
        self.cell(0, 6, "KALOKOT — DIGITAL COUNSEL HUB", align="C", new_x="LMARGIN", new_y="NEXT")
        self.set_font("Helvetica", "", 8)
        self.set_text_color(140, 130, 120)
        self.cell(0, 4, "Virtual Legal Assistance | Know the law. Name the crime.", align="C", new_x="LMARGIN", new_y="NEXT")
        self.line(10, self.get_y() + 2, 200, self.get_y() + 2)
        self.ln(4)

    def footer(self):
        self.set_y(-15)
        self.set_font("Helvetica", "I", 7)
        self.set_text_color(140, 130, 120)
        self.cell(0, 10, f"Generated by KaloKoT Digital Lawyer — {datetime.now().strftime('%Y-%m-%d %H:%M')} | Page {self.page_no()}/{{nb}}", align="C")


class AnalysisPDF(FPDF):
    """Legal analysis report PDF."""

    def header(self):
        self.set_font("Helvetica", "B", 10)
        self.set_text_color(180, 150, 80)
        self.cell(0, 6, "KALOKOT — LEGAL ANALYSIS REPORT", align="C", new_x="LMARGIN", new_y="NEXT")
        self.line(10, self.get_y() + 2, 200, self.get_y() + 2)
        self.ln(4)

    def footer(self):
        self.set_y(-15)
        self.set_font("Helvetica", "I", 7)
        self.set_text_color(140, 130, 120)
        self.cell(0, 10, f"Generated by KaloKoT Digital Lawyer — {datetime.now().strftime('%Y-%m-%d %H:%M')} | Page {self.page_no()}/{{nb}}", align="C")


def generate_complaint_pdf(
    name: str,
    permanent_address: str,
    temporary_address: str,
    citizenship_no: str,
    phone: str,
    email: str,
    complaint_text: str,
    drafted_letter: str,
) -> BytesIO:
    """Generate a formal complaint letter PDF.

    Args:
        name: Complainant full name.
        permanent_address: Permanent address.
        temporary_address: Temporary address.
        citizenship_no: Citizenship certificate number.
        phone: Contact phone number.
        email: Contact email.
        complaint_text: The user's description of the complaint.
        drafted_letter: The drafted legal letter from the LLM.

    Returns:
        BytesIO with the PDF data.
    """
    pdf = ComplaintPDF()
    pdf.alias_nb_pages()
    pdf.set_auto_page_break(auto=True, margin=20)

    # ── Title page ──
    pdf.add_page()
    pdf.set_font("Helvetica", "B", 16)
    pdf.set_text_color(220, 200, 160)
    pdf.ln(30)
    pdf.cell(0, 12, "FORMAL COMPLAINT LETTER", align="C", new_x="LMARGIN", new_y="NEXT")
    pdf.set_font("Helvetica", "", 10)
    pdf.set_text_color(180, 150, 80)
    pdf.ln(4)
    pdf.cell(0, 6, "Under the Constitution of Nepal 2015 and applicable laws", align="C", new_x="LMARGIN", new_y="NEXT")
    pdf.ln(10)

    # ── Complainant Information ──
    pdf.set_font("Helvetica", "B", 11)
    pdf.set_text_color(220, 200, 160)
    pdf.cell(0, 8, "COMPLAINANT DETAILS", new_x="LMARGIN", new_y="NEXT")
    pdf.set_draw_color(180, 150, 80)
    pdf.line(10, pdf.get_y(), 200, pdf.get_y())
    pdf.ln(4)

    pdf.set_font("Helvetica", "", 10)
    pdf.set_text_color(200, 190, 180)
    fields = [
        ("Full Name", name),
        ("Permanent Address", permanent_address),
        ("Temporary Address", temporary_address),
        ("Citizenship No.", citizenship_no),
        ("Phone", phone),
        ("Email", email),
    ]
    for label, value in fields:
        pdf.set_font("Helvetica", "B", 9)
        pdf.cell(45, 7, f"{label}:")
        pdf.set_font("Helvetica", "", 9)
        pdf.cell(0, 7, value, new_x="LMARGIN", new_y="NEXT")
    pdf.ln(6)

    # ── Complaint Summary ──
    pdf.set_font("Helvetica", "B", 11)
    pdf.set_text_color(220, 200, 160)
    pdf.cell(0, 8, "COMPLAINT SUMMARY", new_x="LMARGIN", new_y="NEXT")
    pdf.line(10, pdf.get_y(), 200, pdf.get_y())
    pdf.ln(4)
    pdf.set_font("Helvetica", "", 10)
    pdf.set_text_color(200, 190, 180)
    pdf.multi_cell(0, 6, complaint_text)
    pdf.ln(6)

    # ── Drafted Letter ──
    pdf.set_font("Helvetica", "B", 11)
    pdf.set_text_color(220, 200, 160)
    pdf.cell(0, 8, "DRAFTED COMPLAINT LETTER", new_x="LMARGIN", new_y="NEXT")
    pdf.line(10, pdf.get_y(), 200, pdf.get_y())
    pdf.ln(4)
    pdf.set_font("Helvetica", "", 10)
    pdf.set_text_color(200, 190, 180)
    pdf.multi_cell(0, 6, drafted_letter)

    # ── Disclaimer ──
    pdf.ln(8)
    pdf.line(10, pdf.get_y(), 200, pdf.get_y())
    pdf.ln(3)
    pdf.set_font("Helvetica", "I", 8)
    pdf.set_text_color(140, 130, 120)
    pdf.multi_cell(0, 5, (
        "DISCLAIMER: This document is AI-generated and provided for informational purposes only. "
        "It does not constitute legal advice. Review with a qualified attorney before submitting to any authority."
    ))

    buf = BytesIO()
    pdf.output(buf)
    buf.seek(0)
    return buf


def generate_analysis_report_pdf(
    issue: str,
    analysis_text: str,
) -> BytesIO:
    """Generate a legal analysis report PDF.

    Args:
        issue: The legal issue or question described by the user.
        analysis_text: The lawyer's analysis response.

    Returns:
        BytesIO with the PDF data.
    """
    pdf = AnalysisPDF()
    pdf.alias_nb_pages()
    pdf.set_auto_page_break(auto=True, margin=20)

    pdf.add_page()
    pdf.set_font("Helvetica", "B", 16)
    pdf.set_text_color(220, 200, 160)
    pdf.ln(20)
    pdf.cell(0, 12, "LEGAL ANALYSIS REPORT", align="C", new_x="LMARGIN", new_y="NEXT")
    pdf.set_font("Helvetica", "", 10)
    pdf.set_text_color(180, 150, 80)
    pdf.ln(4)
    pdf.cell(0, 6, f"Prepared on {datetime.now().strftime('%Y-%m-%d at %H:%M')}", align="C", new_x="LMARGIN", new_y="NEXT")
    pdf.ln(10)

    # ── Issue ──
    pdf.set_font("Helvetica", "B", 11)
    pdf.set_text_color(220, 200, 160)
    pdf.cell(0, 8, "LEGAL ISSUE / QUESTION", new_x="LMARGIN", new_y="NEXT")
    pdf.set_draw_color(180, 150, 80)
    pdf.line(10, pdf.get_y(), 200, pdf.get_y())
    pdf.ln(4)
    pdf.set_font("Helvetica", "", 10)
    pdf.set_text_color(200, 190, 180)
    pdf.multi_cell(0, 6, issue)
    pdf.ln(6)

    # ── Analysis ──
    pdf.set_font("Helvetica", "B", 11)
    pdf.set_text_color(220, 200, 160)
    pdf.cell(0, 8, "LEGAL ANALYSIS", new_x="LMARGIN", new_y="NEXT")
    pdf.line(10, pdf.get_y(), 200, pdf.get_y())
    pdf.ln(4)
    pdf.set_font("Helvetica", "", 10)
    pdf.set_text_color(200, 190, 180)
    pdf.multi_cell(0, 6, analysis_text)

    # ── Disclaimer ──
    pdf.ln(8)
    pdf.line(10, pdf.get_y(), 200, pdf.get_y())
    pdf.ln(3)
    pdf.set_font("Helvetica", "I", 8)
    pdf.set_text_color(140, 130, 120)
    pdf.multi_cell(0, 5, (
        "DISCLAIMER: This analysis is AI-generated and provided for informational purposes only. "
        "It does not constitute legal advice. Consult a qualified attorney for legal counsel."
    ))

    buf = BytesIO()
    pdf.output(buf)
    buf.seek(0)
    return buf
