"""Report generator — produces human-readable risk reports from RiskReport data.

Supports three output formats:
- Plain text (terminal-friendly)
- HTML (browser-friendly with inline styles)
- Terminal heatmap (compact section-by-section view)
"""

from __future__ import annotations

import html

from ..shared.models import RiskReport, RiskLevel, Severity


class ReportGenerator:
    """Generates formatted reports from risk analysis results."""

    def generate_text(self, report: RiskReport) -> str:
        """Generate a plain-text report suitable for terminal display.

        Args:
            report: The RiskReport to render.

        Returns:
            A multi-line string with the full report.
        """
        lines = []
        lines.append("=" * 60)
        lines.append("OPEN TENDER CORRUPTION RISK REPORT")
        lines.append("=" * 60)
        lines.append("")
        lines.append(f"Tender: {report.tender.title}")
        if report.tender.reference_no:
            lines.append(f"Reference: {report.tender.reference_no}")
        if report.tender.procuring_entity:
            lines.append(
                f"Procuring Entity: {report.tender.procuring_entity}"
            )
        if report.tender.estimated_value:
            lines.append(
                f"Estimated Value: {report.tender.estimated_value}"
            )
        lines.append("")
        lines.append(
            f"OVERALL RISK: {self._format_risk(report.overall_risk)}"
        )
        lines.append("")

        # ── Section scores ──────────────────────────────────────────
        lines.append("-" * 60)
        lines.append("SECTION RISK SCORES:")
        lines.append("-" * 60)
        for section, score in report.section_scores.items():
            icon = self._risk_emoji(score)
            name = section.replace("_", " ").title()
            lines.append(f"  {icon} {name}: {score.upper()}")
        lines.append("")

        # ── Flagged clauses ─────────────────────────────────────────
        if report.flagged_clauses:
            lines.append("-" * 60)
            lines.append("FLAGGED CLAUSES / RED FLAGS:")
            lines.append("-" * 60)
            for i, flag in enumerate(report.flagged_clauses, 1):
                severity_icon = self._severity_icon(flag.severity)
                lines.append("")
                lines.append(
                    f"  #{i} {severity_icon} "
                    f"[{flag.severity.upper()}] {flag.label}"
                )
                lines.append(f"     {flag.description}")
                if flag.law_reference:
                    lines.append(f"     Law: {flag.law_reference}")
                lines.append(f"     Location: {flag.location}")
                lines.append(f"     Suggestion: {flag.suggestion}")
                if flag.excerpt:
                    excerpt = (
                        flag.excerpt[:150] + ("..." if len(flag.excerpt) > 150 else "")
                    )
                    lines.append(f'     Excerpt: "{excerpt}"')
        else:
            lines.append("No red flags detected.")

        lines.append("")
        lines.append("=" * 60)
        lines.append(
            "Report generated by OpenTender + Counsel"
            " — AI-assisted analysis"
        )
        lines.append("=" * 60)

        return "\n".join(lines)

    def generate_html(self, report: RiskReport) -> str:
        """Generate a minimal self-contained HTML report for browser viewing.

        Uses inline styles so no external CSS is required.

        Args:
            report: The RiskReport to render.

        Returns:
            A complete HTML document as a string.
        """
        # ── Section scores HTML ─────────────────────────────────────
        score_html = ""
        for section, score in report.section_scores.items():
            name = html.escape(section.replace("_", " ").title())
            color = self._risk_color(score)
            score_html += (
                '    <div style="display:flex;'
                'justify-content:space-between;'
                'padding:6px 0;border-bottom:1px solid #eee;">'
                f"<span>{name}</span>"
                f'<span style="color:{color};font-weight:bold;">'
                f"{score.upper()}</span></div>\n"
            )

        # ── Flagged clauses HTML ────────────────────────────────────
        flags_html = ""
        for flag in report.flagged_clauses:
            color = self._severity_color(flag.severity)
            law_ref = (
                f'<div><b>Law:</b> {html.escape(flag.law_reference)}</div>'
                if flag.law_reference
                else ""
            )
            flags_html += f"""
    <div style="border-left:4px solid {color};padding:12px;
                margin:12px 0;background:#f9f9f9;border-radius:4px;">
        <div style="font-weight:bold;color:{color};">
            {html.escape(flag.label)} [{flag.severity.upper()}]
        </div>
        <div style="margin:6px 0;">{html.escape(flag.description)}</div>
        <div style="font-size:0.9em;color:#666;">
            {law_ref}
            <div><b>Location:</b> {html.escape(flag.location)}</div>
            <div><b>Suggestion:</b> {html.escape(flag.suggestion)}</div>
        </div>
    </div>"""

        overall_color = self._risk_color(report.overall_risk)

        return f"""<!DOCTYPE html>
<html><head><meta charset="utf-8">
<title>Risk Report - {html.escape(report.tender.title[:60])}</title>
<style>
body {{ font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI',
       Roboto, sans-serif; max-width: 800px; margin: 20px auto;
       padding: 0 20px; color: #222; }}
h1 {{ font-size: 1.5em; }}
.badge {{ display:inline-block; padding:4px 12px; border-radius:20px;
         color:white; font-weight:bold; font-size:1.1em; }}
</style></head>
<body>
<h1>🛡️ OpenTender + Counsel — Corruption Risk Report</h1>
<table style="width:100%; margin:12px 0;">
    <tr><td><b>Tender:</b></td>
        <td>{html.escape(report.tender.title)}</td></tr>
    {f'<tr><td><b>Reference:</b></td><td>{html.escape(report.tender.reference_no)}</td></tr>' if report.tender.reference_no else ''}
    {f'<tr><td><b>Entity:</b></td><td>{html.escape(report.tender.procuring_entity)}</td></tr>' if report.tender.procuring_entity else ''}
    {f'<tr><td><b>Value:</b></td><td>{html.escape(report.tender.estimated_value)}</td></tr>' if report.tender.estimated_value else ''}
</table>

<div style="margin:20px 0;padding:20px;background:#f0f0f0;
            border-radius:8px;text-align:center;">
    <div style="font-size:0.9em;color:#666;">Overall Risk Level</div>
    <div class="badge" style="background:{overall_color};
         font-size:1.5em;margin:8px 0;">
        {report.overall_risk.upper()}
    </div>
</div>

<h2>Section Scores</h2>
{score_html}

<h2>Red Flags ({len(report.flagged_clauses)})</h2>
{flags_html if flags_html else '<p>No red flags detected. ✓</p>'}

<hr style="margin:30px 0;">
<div style="font-size:0.8em;color:#999;text-align:center;">
    Generated by OpenTender + Counsel — AI-assisted corruption
    risk analysis. This is not legal advice. Consult a qualified
    attorney for legal action.
</div>
</body></html>"""

    def generate_heatmap(self, report: RiskReport) -> str:
        """Generate a compact section-by-section risk heatmap.

        Terminal-friendly; uses emoji bars for colour.

        Args:
            report: The RiskReport to render.

        Returns:
            A multi-line string with the heatmap.
        """
        lines = []
        lines.append("")
        lines.append("  RISK HEATMAP")
        lines.append("  " + "─" * 40)

        sections_in_order = [
            "details",
            "specification",
            "budget",
            "timeline",
            "evaluation_criteria",
            "terms_and_conditions",
        ]
        for section in sections_in_order:
            score = report.section_scores.get(section, RiskLevel.GREEN)
            name = section.replace("_", " ").title()
            bar = self._risk_bar(score)
            lines.append(f"  {bar} {name}")

        lines.append("  " + "─" * 40)
        overall = report.overall_risk
        bar = self._risk_bar(overall)
        lines.append(f"  {bar} OVERALL: {overall.upper()}")
        lines.append("")
        return "\n".join(lines)

    # ── Formatting helpers ──────────────────────────────────────────

    def _format_risk(self, level: RiskLevel) -> str:
        """Format a risk level with an emoji prefix."""
        icon = self._risk_emoji(level)
        return f"{icon} {level.upper()}"

    def _risk_emoji(self, level: RiskLevel) -> str:
        """Return a coloured-circle emoji for a risk level."""
        return {"green": "🟢", "yellow": "🟡", "red": "🔴"}.get(
            level.value, "⚪"
        )

    def _severity_icon(self, severity: Severity) -> str:
        """Return an icon emoji for a severity level."""
        return {
            "low": "ℹ️",
            "medium": "⚠️",
            "high": "🚨",
            "critical": "💀",
        }.get(severity.value, "⚪")

    def _risk_color(self, level: RiskLevel) -> str:
        """Return a CSS hex colour for a risk level."""
        return {"green": "#22c55e", "yellow": "#eab308", "red": "#ef4444"}.get(
            level.value, "#999"
        )

    def _severity_color(self, severity: Severity) -> str:
        """Return a CSS hex colour for a severity level."""
        return {
            "low": "#6b7280",
            "medium": "#eab308",
            "high": "#f97316",
            "critical": "#ef4444",
        }.get(severity.value, "#999")

    def _risk_bar(self, level: RiskLevel) -> str:
        """Return a coloured-circle emoji (alias for _risk_emoji)."""
        return self._risk_emoji(level)
